apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: k8s-bigdata
data:
  YARN_CONF_yarn_log_server_url: https://historyserver:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_hostname: $(RESOURCEMANAGER_SERVICE_HOST)
  YARN_CONF_yarn_resourcemanager_address: resourcemanager:8032
  YARN_CONF_yarn_resourcemanager_scheduler_address: resourcemanager:8030
  YARN_CONF_yarn_resourcemanager_resource__tracker_address: resourcemanager:8031
  YARN_CONF_yarn_timeline___service_hostname: historyserver
  MAPRED_CONF_mapred_child_java_opts: "-Xmx4096m"
  MAPRED_CONF_mapreduce_jobhistory_address: historyserver:10020
  MAPRED_CONF_mapreduce_jobhistory_webapp_address: historyserver:19888
  SPARK_NUM_CORES: "9"
  SPARK_DRIVER_MEMORY: "2g"
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  SPARK_MASTER: "spark://namenode:7077"
  HADOOP_URL: "hdfs://namenode:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: k8s-bigdata
spec:
  selector:
    app: namenode
  externalName: namenode
  ports:
    - name: web-ui
      port: 9870
      targetPort: 9870
    - name: namenode-ipc
      port: 9000
      targetPort: 9000
    - name: web-ui-spark
      port: 8080
      targetPort: 8080
    - name: master-spark
      port: 7077
      targetPort: 7077
    - name: master-rest-spark
      port: 6066
      targetPort: 6066
    - name: history-server
      port: 18080
      targetPort: 18080
    - name: general
      port: 50070 
      targetPort: 50070
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: k8s-bigdata
spec:
    selector:
      app: resourcemanager
    externalName: resourcemanager
    ports:
      - name: yarn-web-ui
        port: 8088
        targetPort: 8088
      - name: yarn-scheduler
        port: 8030
        targetPort: 8030
      - name: yarn-jobtracker
        port: 8031
        targetPort: 8031
      - name: yarn
        port: 8032
        targetPort: 8032 
---
apiVersion: v1
kind: Service
metadata:
  name: historyserver
  namespace: k8s-bigdata
spec:
  selector:
    app: historyserver
  externalName: historyserver
  ports:
    - name: web-ui
      port: 19888
      targetPort: 19888
    - name: ipc
      port: 10200
      targetPort: 10200
    - name: other-web-ui
      port: 8188
      targetPort: 8188
---
apiVersion: v1
kind: Service
metadata: 
  name: datanode
  namespace: k8s-bigdata
spec:
  selector:
    app: datanode
  ports:
    - name: spark-worker-ui
      port: 8081
      targetPort: 8081
    - name: datanode-ipc
      port: 9864
      targetPort: 9864
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode
  namespace: k8s-bigdata
  labels:
    app: spark
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: namenode
  namespace: k8s-bigdata
  labels:
    app: namenode
spec:
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: namenode
  containers:
  - name: namenode
    image: mayanktiwari09/hadoop-namenode:1.3
    imagePullPolicy: Always
    resources:
      limits:
        memory: "16Gi"
        cpu: "8"
    env:
    - name: YARN_CONF_yarn_log_server_url
      value: https://$(HISTORYSERVER_SERVICE_HOST):8188/applicationhistory/logs/
    - name: YARN_CONF_yarn_resourcemanager_address
      value: $(RESOURCEMANAGER_SERVICE_HOST):8032
    - name: YARN_CONF_yarn_resourcemanager_hostname
      value: $(RESOURCEMANAGER_SERVICE_HOST)
    - name: YARN_CONF_yarn_resourcemanager_scheduler_address
      value: $(RESOURCEMANAGER_SERVICE_HOST):8030
    - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
      value: $(RESOURCEMANAGER_SERVICE_HOST):8031
    - name: YARN_CONF_yarn_timeline___service_hostname
      value: $(HISTORYSERVER_SERVICE_HOST)
    - name: MAPRED_CONF_mapred_child_java_opts
      value: "-Xmx4096m"
    - name: MAPRED_CONF_mapreduce_jobhistory_address
      value: $(HISTORYSERVER_SERVICE_HOST):10020
    - name: MAPRED_CONF_mapreduce_jobhistory_webapp_address
      value: $(HISTORYSERVER_SERVICE_HOST):19888
    - name: SPARK_NUM_CORES
      value: "9"
    - name: SPARK_DRIVER_MEMORY
      value: "2g"
    - name: CORE_CONF_fs_defaultFS
      value: hdfs://localhost:9000
    - name: SPARK_MASTER
      value: spark://localhost:7077
    - name: HADOOP_URL
      value: hdfs://localhost:9000
    ports:
      - containerPort: 9870
      - containerPort: 9000
      - containerPort: 9866
      - containerPort: 8080
      - containerPort: 7077
      - containerPort: 6066
      - containerPort: 18080
    volumeMounts:
      - name: vol
        mountPath: /hadoop/dfs/name
  dnsConfig:
    options:
      - name: ndots
        value: "0" 
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: datanode
  namespace: k8s-bigdata
  labels:
    app: datanode
spec:
  serviceName: "datanode"
  replicas: 4
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - image: mayanktiwari09/hadoop-datanode
          name: datanode
          resources:
            limits:
              memory: "16Gi"
              cpu: "8"
          env:
          - name: SERVICE_PRECONDITION
            value: "$(NAMENODE_SERVICE_HOST):50070 $(NAMENODE_SERVICE_HOST):9000 $(NAMENODE_SERVICE_HOST):8080"
          - name: NUM_CORES
            value: "8"
          - name: YARN_CONF_yarn_log_server_url
            value: https://$(HISTORYSERVER_SERVICE_HOST):8188/applicationhistory/logs/
          - name: YARN_CONF_yarn_resourcemanager_address
            value: $(RESOURCEMANAGER_SERVICE_HOST):8032
          - name: YARN_CONF_yarn_resourcemanager_hostname
            value: $(RESOURCEMANAGER_SERVICE_HOST)
          - name: YARN_CONF_yarn_resourcemanager_scheduler_address
            value: $(RESOURCEMANAGER_SERVICE_HOST):8030
          - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
            value: $(RESOURCEMANAGER_SERVICE_HOST):8031
          - name: YARN_CONF_yarn_timeline___service_hostname
            value: $(HISTORYSERVER_SERVICE_HOST)
          - name: MAPRED_CONF_mapred_child_java_opts
            value: "-Xmx4096m"
          - name: MAPRED_CONF_mapreduce_jobhistory_address
            value: $(HISTORYSERVER_SERVICE_HOST):10020
          - name: MAPRED_CONF_mapreduce_jobhistory_webapp_address
            value: $(HISTORYSERVER_SERVICE_HOST):19888
          - name: SPARK_NUM_CORES
            value: "9"
          - name: SPARK_DRIVER_MEMORY
            value: "2g"
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://$(NAMENODE_SERVICE_HOST):9000
          - name: SPARK_MASTER
            value: spark://$(NAMENODE_SERVICE_HOST):7077
          - name: HADOOP_URL
            value: hdfs://$(NAMENODE_SERVICE_HOST):9000
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: vol 
          ports:
            - containerPort: 8081
            - containerPort: 4040
            - containerPort: 50020
        - image: mayanktiwari09/hadoop-nodemanager
          name: nodemanager
          resources:
            limits:
              memory: "6Gi"
              cpu: "3"
          ports:
            - containerPort: 45454
          env:      
          - name: YARN_CONF_yarn_log_server_url
            value: https://$(HISTORYSERVER_SERVICE_HOST):8188/applicationhistory/logs/
          - name: YARN_CONF_yarn_resourcemanager_address
            value: $(RESOURCEMANAGER_SERVICE_HOST):8032
          - name: YARN_CONF_yarn_resourcemanager_hostname
            value: $(RESOURCEMANAGER_SERVICE_HOST)
          - name: YARN_CONF_yarn_resourcemanager_scheduler_address
            value: $(RESOURCEMANAGER_SERVICE_HOST):8030
          - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
            value: $(RESOURCEMANAGER_SERVICE_HOST):8031
          - name: YARN_CONF_yarn_timeline___service_hostname
            value: $(HISTORYSERVER_SERVICE_HOST)
          - name: MAPRED_CONF_mapred_child_java_opts
            value: "-Xmx4096m"
          - name: MAPRED_CONF_mapreduce_jobhistory_address
            value: $(HISTORYSERVER_SERVICE_HOST):10020
          - name: MAPRED_CONF_mapreduce_jobhistory_webapp_address
            value: $(HISTORYSERVER_SERVICE_HOST):19888
          - name: SPARK_NUM_CORES
            value: "9"
          - name: SPARK_DRIVER_MEMORY
            value: "2g"
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://$(NAMENODE_SERVICE_HOST):9000
          - name: SPARK_MASTER
            value: spark://$(NAMENODE_SERVICE_HOST):7077
          - name: HADOOP_URL
            value: hdfs://$(NAMENODE_SERVICE_HOST):9000
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVICE_PRECONDITION
            value: "$(NAMENODE_SERVICE_HOST):50070 $(NAMENODE_SERVICE_HOST):9000 $(RESOURCEMANAGER_SERVICE_HOST):8088 $(POD_NAME):50020"
      dnsConfig:
        options:
          - name: ndots
            value: "0"
      volumes:
        - name: vol
  volumeClaimTemplates:
  - metadata:
      name: vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 60Gi 
---
apiVersion: v1
kind: Pod
metadata:
  name: resourcemanager
  namespace: k8s-bigdata
  labels: 
    app: resourcemanager
spec: 
  containers:
    - image: mayanktiwari09/hadoop-resourcemanager
      name: resourcemanager
      resources:
            limits:
              memory: "8Gi"
              cpu: "3"
      env:
      - name: SERVICE_PRECONDITION
        value: "$(NAMENODE_SERVICE_HOST):50070 $(NAMENODE_SERVICE_HOST):9000 $(DATANODE_SERVICE_HOST):8081"
      - name: YARN_CONF_yarn_log_server_url
        value: https://$(HISTORYSERVER_SERVICE_HOST):8188/applicationhistory/logs/
      - name: YARN_CONF_yarn_resourcemanager_address
        value: $(RESOURCEMANAGER_SERVICE_HOST):8032
      - name: YARN_CONF_yarn_resourcemanager_hostname
        value: $(RESOURCEMANAGER_SERVICE_HOST)
      - name: YARN_CONF_yarn_resourcemanager_scheduler_address
        value: $(RESOURCEMANAGER_SERVICE_HOST):8030
      - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
        value: $(RESOURCEMANAGER_SERVICE_HOST):8031
      - name: YARN_CONF_yarn_timeline___service_hostname
        value: $(HISTORYSERVER_SERVICE_HOST)
      - name: MAPRED_CONF_mapred_child_java_opts
        value: "-Xmx4096m"
      - name: MAPRED_CONF_mapreduce_jobhistory_address
        value: $(HISTORYSERVER_SERVICE_HOST):10020
      - name: MAPRED_CONF_mapreduce_jobhistory_webapp_address
        value: $(HISTORYSERVER_SERVICE_HOST):19888
      - name: SPARK_NUM_CORES
        value: "9"
      - name: SPARK_DRIVER_MEMORY
        value: "2g"
      - name: CORE_CONF_fs_defaultFS
        value: hdfs://$(NAMENODE_SERVICE_HOST):9000
      - name: SPARK_MASTER
        value: spark://$(NAMENODE_SERVICE_HOST):7077
      - name: HADOOP_URL
        value: hdfs://$(NAMENODE_SERVICE_HOST):9000
      ports:
        - containerPort: 8088
        - containerPort: 8031
        - containerPort: 8032
        - containerPort: 8030
      readinessProbe:
        exec:
          command:
          - curl 
          - -sI 
          - datanode:8081
        initialDelaySeconds: 2
        periodSeconds: 3
  dnsConfig:
    options:
      - name: ndots
        value: "0" 
---
apiVersion: v1
kind: Pod
metadata:
  name: historyserver
  namespace: k8s-bigdata
  labels: 
    app: historyserver
spec:
  containers:
    - image: mayanktiwari09/hadoop-historyserver
      name: historyserver
      resources:
            limits:
              memory: "8Gi"
              cpu: "3"
      env:
      - name: SERVICE_PRECONDITION
        value: "$(NAMENODE_SERVICE_HOST):50070 $(NAMENODE_SERVICE_HOST):9000 $(DATANODE_SERVICE_HOST):8081"
      - name: YARN_CONF_yarn_log_server_url
        value: https://$(HISTORYSERVER_SERVICE_HOST):8188/applicationhistory/logs/
      - name: YARN_CONF_yarn_resourcemanager_address
        value: $(RESOURCEMANAGER_SERVICE_HOST):8032
      - name: YARN_CONF_yarn_resourcemanager_hostname
        value: $(RESOURCEMANAGER_SERVICE_HOST)
      - name: YARN_CONF_yarn_resourcemanager_scheduler_address
        value: $(RESOURCEMANAGER_SERVICE_HOST):8030
      - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
        value: $(RESOURCEMANAGER_SERVICE_HOST):8031
      - name: YARN_CONF_yarn_timeline___service_hostname
        value: $(HISTORYSERVER_SERVICE_HOST)
      - name: MAPRED_CONF_mapred_child_java_opts
        value: "-Xmx4096m"
      - name: MAPRED_CONF_mapreduce_jobhistory_address
        value: $(HISTORYSERVER_SERVICE_HOST):10020
      - name: MAPRED_CONF_mapreduce_jobhistory_webapp_address
        value: $(HISTORYSERVER_SERVICE_HOST):19888
      - name: SPARK_NUM_CORES
        value: "9"
      - name: SPARK_DRIVER_MEMORY
        value: "2g"
      - name: CORE_CONF_fs_defaultFS
        value: hdfs://$(NAMENODE_SERVICE_HOST):9000
      - name: SPARK_MASTER
        value: spark://$(NAMENODE_SERVICE_HOST):7077
      - name: HADOOP_URL
        value: hdfs://$(NAMENODE_SERVICE_HOST):9000
      ports:
        - containerPort: 8188
        - containerPort: 19888
        - containerPort: 10200  
      volumeMounts:
        - name: historyserver
          mountPath: /hadoop/yarn/timeline
  dnsConfig:
    options:
      - name: ndots
        value: "0"
  volumes:
    - name: historyserver
